#!/bin/bash

cd busybox-src || exit 1
make defconfig

# Make it static and don't create symlinks.
sed -i 's/^#.*CONFIG_STATIC.*/CONFIG_STATIC=y/' .config
sed -i 's/^.*CONFIG_INSTALL_APPLET_SYMLINKS.*/# CONFIG_INSTALL_APPLET_SYMLINKS is not set/' .config
sed -i 's/^#.*CONFIG_INSTALL_APPLET_DONT.*/CONFIG_INSTALL_APPLET_DONT=y/' .config

# Musl.
echo 'CONFIG_CROSS_COMPILER_PREFIX="musl-""' >> .config
sudo ln -s "$(which ar)" /usr/bin/musl-ar
sudo ln -s "$(which strip)" /usr/bin/musl-strip
export CC="musl-gcc"

make -j"$(nproc)"
make install
mv _install/bin/busybox ../
