#!/bin/bash

cd busybox-src || exit 1
make defconfig

# Make it static and don't create symlinks.
sed -i 's/^#.*CONFIG_STATIC.*/CONFIG_STATIC=y/' .config
sed -i 's/^.*CONFIG_INSTALL_APPLET_SYMLINKS.*/# CONFIG_INSTALL_APPLET_SYMLINKS is not set/' .config
sed -i 's/^#.*CONFIG_INSTALL_APPLET_DONT.*/CONFIG_INSTALL_APPLET_DONT=y/' .config

# Musl.
#sed -i 's/^#.*CONFIG_CROSS_COMPILER_PREFIX.*/CONFIG_CROSS_COMPILER_PREFIX=musl-/' .config
echo 'CONFIG_CROSS_COMPILER_PREFIX="musl-""' >> .config

make -j"$(nproc)"
make install
mv _install/bin/busybox ../
