#!/bin/sh -e
echo "Busybox version $1"
wget https://busybox.net/downloads/busybox-"$1".tar.bz2
mkdir busybox-src
(
    cd busybox-src || exit 1
    tar --strip-components=1 -xf ../busybox-"$1".tar.bz2
)
