name: release-multi

on:
  workflow_dispatch:
    inputs:
      busybox_version:
        description: 'Busybox version'
        required: true
        default: '1.35.0'
      tag_name:
        description: 'Tag/Release name'
        required: true
        default: '1.35.0'

jobs:
  x86_64-glibc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup environment variable
        run: |
          GET_VER="${{ github.event.inputs.busybox_version }}"
          GET_TAG_NAME="${{ github.event.inputs.tag_name }}"
          echo "BUSYBOX_VERSION=$GET_VER" >> $GITHUB_ENV
          echo "TAG_NAME=$GET_TAG_NAME" >> $GITHUB_ENV
      - name: Obtain Busybox source tarball
        run: |
          scripts/obtain_busybox ${{ env.BUSYBOX_VERSION }}
      - name: Patch Busybox
        run: |
          scripts/patch_busybox
      - name: Build Busybox
        run: |
          scripts/build_busybox_glibc.x86_64
      - name: Release Busybox binary
        uses: ncipollo/release-action@v1
        with:
          name: "Release ${{ env.TAG_NAME }}"
          owner: ${{ env.OWNER }}
          tag: "${{ env.TAG_NAME }}"
          commit: "master"
          draft: true
          artifacts: "busybox_glibc.x86_64"
          artifactContentType: "application/octet-stream"
          body: "${{ env.BUSYBOX_VERSION }}"
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
  x86_64-musl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup environment variable
        run: |
          GET_VER="${{ github.event.inputs.busybox_version }}"
          GET_TAG_NAME="${{ github.event.inputs.tag_name }}"
          echo "BUSYBOX_VERSION=$GET_VER" >> $GITHUB_ENV
          echo "TAG_NAME=$GET_TAG_NAME" >> $GITHUB_ENV
      - name: Obtain Busybox source tarball
        run: |
          scripts/obtain_busybox ${{ env.BUSYBOX_VERSION }}
      - name: Patch Busybox
        run: |
          scripts/patch_busybox
      - name: Build Busybox
        uses: addnab/docker-run-action@v3
        with:
          image: alpine:3.14
          options: -v ${{ github.workspace }}:/work
          shell: sh
          run: |
            apk update
            apk upgrade
            apk add build-base
            apk add linux-headers
            cd work
            scripts/build_busybox_musl.x86_64
      - name: Release Busybox binary
        uses: ncipollo/release-action@v1
        with:
          name: "Release ${{ env.TAG_NAME }}"
          owner: ${{ env.OWNER }}
          tag: "${{ env.TAG_NAME }}"
          commit: "master"
          draft: true
          artifacts: "busybox_musl.x86_64"
          artifactContentType: "application/octet-stream"
          body: "${{ env.BUSYBOX_VERSION }}"
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
