name: release

on:
  push:
   tags:
   - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Obtain Busybox source tarball
        run: |
          echo "busybox_version=$(cat busybox_version)" >> $GITHUB_ENV
          bash obtain_busybox "${{ env.busybox_version }}"
      - name: Patch Busybox
        run: |
          bash patch_busybox
      - name: Build Busybox
        run: |
          bash build_busybox
      - name: Release Busybox binary
        uses: ncipollo/release-action@v1
        with:
          name: "Release ${{ env.busybox_version }}"
          draft: true
          artifacts: "busybox"
          artifactContentType: "application/octet-stream"
          bodyFile: "busybox"
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
